-- Stage 6 audit writes are performed by the reviewed SECURITY INVOKER RPCs.
-- Do not grant a general browser/Data API insert path for audit_events.
-- Existing table RLS and grants remain unchanged; audit rows stay immutable to clients.
